/* Console shell: routing, rendering and governance display.
 *
 * registry.json is GENERATED by build_registry.py from the records on disk —
 * the review queue and every status come from evidence, not from hand-edited
 * markup. The console is a pure renderer: it never invents a status, and it
 * shows the generator's drift notes instead of hiding them. */

import { PANELS, renderPanel } from './panels.js';

const $ = (sel, root = document) => root.querySelector(sel);
const esc = (value) =>
  String(value ?? '').replace(
    /[&<>"']/g,
    (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char],
  );

const state = {
  registry: null,
  decisions: new Map(),
  consumers: [],
  flat: [],
};

/* ── Load ────────────────────────────────────────────────────── */

async function loadJson(path, fallback = null) {
  try {
    const response = await fetch(path);
    if (!response.ok) throw new Error(String(response.status));
    return await response.json();
  } catch {
    return fallback;
  }
}

async function boot() {
  const [registry, pre, post, consumers] = await Promise.all([
    loadJson('./registry.json'),
    loadJson('../governance/decisions.json', { decisions: [] }),
    loadJson('../governance/post-cutover-decisions.json', { decisions: [] }),
    loadJson('../governance/consumer-register.json', { consumers: [] }),
  ]);

  if (!registry) {
    $('#panel').innerHTML =
      '<div class="flag">Could not load <code>registry.json</code>. Serve over HTTP and run <code>python3 brand-kit/app/build_registry.py</code>.</div>';
    return;
  }

  state.registry = registry;
  state.consumers = consumers?.consumers ?? [];
  for (const record of [...(pre?.decisions ?? []), ...(post?.decisions ?? [])]) {
    state.decisions.set(record.id, record);
  }

  state.flat = [];
  for (const zone of registry.zones) {
    for (const group of zone.groups ?? []) {
      for (const item of group.items ?? []) {
        state.flat.push({ ...item, zoneId: zone.id, zoneLabel: zone.label, groupLabel: group.label });
      }
    }
  }

  renderChrome();
  renderSidebar();
  route();
}

/* ── Chrome ──────────────────────────────────────────────────── */

const tone = (status) => state.registry.statuses[status]?.tone ?? 'idle';
const statusLabel = (status) => state.registry.statuses[status]?.label ?? status;
const badge = (status) =>
  `<span class="badge" data-tone="${tone(status)}">${esc(statusLabel(status))}</span>`;

function queueItems() {
  const zone = state.registry.zones.find((entry) => entry.id === 'review');
  return (zone?.groups ?? []).find((group) => group.id === 'queue')?.items ?? [];
}

function renderChrome() {
  const { currentRelease, currentReleaseState } = state.registry.system;
  $('#rel-chip').textContent = `${currentRelease} · ${currentReleaseState}`;

  $('#legend-body').innerHTML = Object.entries(state.registry.statuses)
    .map(([key, meta]) => `<div><dt>${badge(key)}</dt><dd>${esc(meta.meaning)}</dd></div>`)
    .join('');

  const legend = $('#legend');
  const open = () => {
    legend.hidden = false;
    $('#legend-close').focus();
  };
  const close = () => {
    legend.hidden = true;
    $('#legend-open').focus();
  };
  $('#legend-open').addEventListener('click', open);
  $('#legend-close').addEventListener('click', close);
  legend.addEventListener('click', (event) => {
    if (event.target === legend) close();
  });

  $('#nav-toggle').addEventListener('click', () => {
    const expanded = document.body.classList.toggle('nav-open');
    $('#nav-toggle').setAttribute('aria-expanded', String(expanded));
  });

  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') {
      if (!legend.hidden) close();
      document.body.classList.remove('nav-open');
    }
    if (
      event.key === '/' &&
      !event.metaKey &&
      !event.ctrlKey &&
      !/^(INPUT|TEXTAREA)$/.test(document.activeElement?.tagName ?? '')
    ) {
      event.preventDefault();
      $('#search').focus();
    }
  });

  wireSearch();
}

function renderSidebar() {
  const nav = $('#sidebar');
  const queued = queueItems().length;

  const zoneHtml = state.registry.zones
    .map((zone) => {
      const isReview = zone.id === 'review';
      const count = isReview
        ? `<span class="zone__count" data-empty="${queued === 0}">${queued}</span>`
        : '';

      const groups = (zone.groups ?? [])
        .map((group) => {
          if (!group.items?.length) return '';
          const showLabel = (zone.groups ?? []).filter((g) => g.items?.length).length > 1;
          const links = group.items
            .map((item) => {
              const mark = item.flag
                ? '<span class="flagdot" title="Needs attention"></span>'
                : `<span class="dot" data-tone="${tone(item.status)}"></span>`;
              return `<a class="navlink" href="#/item/${esc(zone.id)}/${esc(item.id)}" data-id="${esc(item.id)}">
                        <span>${esc(item.name)}</span>${mark}
                      </a>`;
            })
            .join('');
          return `${showLabel ? `<p class="group__label">${esc(group.label)}</p>` : ''}${links}`;
        })
        .join('');

      const empty = isReview && queued === 0
        ? `<p class="zone__empty">Queue is empty — nothing is waiting on you.</p>`
        : '';

      return `<section class="zone">
                <div class="zone__head"><span class="zone__label">${esc(zone.label)}</span>${count}</div>
                ${groups || empty || `<a class="navlink" href="#/zone/${esc(zone.id)}"><span>Overview</span></a>`}
              </section>`;
    })
    .join('');

  nav.innerHTML = `
    <section class="zone">
      <a class="navlink" href="#/dashboard" data-id="__dashboard"><span>Dashboard</span></a>
      <a class="navlink" href="#/how" data-id="__how"><span>How this works</span></a>
      <a class="navlink" href="#/ingest" data-id="__ingest"><span>Consumers &amp; ingest</span></a>
    </section>
    ${zoneHtml}
    <p class="gen-note">registry generated ${esc(String(state.registry.generatedAt ?? '').slice(0, 16).replace('T', ' '))} ·
      <span class="mono">build_registry.py</span></p>
  `;
}

function markCurrent(id) {
  for (const link of document.querySelectorAll('.navlink')) {
    link.setAttribute('aria-current', String(link.dataset.id === id));
  }
}

/* ── Routing ─────────────────────────────────────────────────── */

function route() {
  const hash = location.hash.replace(/^#/, '') || '/dashboard';
  const parts = hash.split('/').filter(Boolean);
  document.body.classList.remove('nav-open');

  if (parts[0] === 'item' && parts[1] && parts[2]) {
    const item = state.flat.find((entry) => entry.zoneId === parts[1] && entry.id === parts[2]);
    if (item) {
      renderItem(item);
      markCurrent(item.id);
      return;
    }
  }
  if (parts[0] === 'zone' && parts[1]) {
    const zone = state.registry.zones.find((entry) => entry.id === parts[1]);
    if (zone) {
      renderZone(zone);
      markCurrent(null);
      return;
    }
  }
  if (parts[0] === 'how') {
    renderHow();
    markCurrent('__how');
    return;
  }
  if (parts[0] === 'ingest') {
    renderIngest();
    markCurrent('__ingest');
    return;
  }
  renderDashboard();
  markCurrent('__dashboard');
}

window.addEventListener('hashchange', () => {
  route();
  window.scrollTo({ top: 0 });
});

/* ── Dashboard ───────────────────────────────────────────────── */

function renderDashboard() {
  const counts = {};
  for (const item of state.flat) counts[item.status] = (counts[item.status] ?? 0) + 1;
  const canonical = counts.canonical ?? 0;
  const nonProduction = counts['non-production'] ?? 0;
  const deferred = counts.deferred ?? 0;

  const decided = [...state.decisions.values()].sort((a, b) =>
    String(b.approvedAt).localeCompare(String(a.approvedAt)),
  );
  const queued = queueItems();
  const drift = state.registry.drift ?? [];

  const consumer = state.consumers[0];
  const sysRelease = state.registry.system.currentRelease;
  const consumerRelease = consumer?.designSystemCandidate?.version;
  const inSync = consumerRelease === sysRelease;

  const total = canonical + nonProduction + deferred || 1;
  const pct = (value) => `${((value / total) * 100).toFixed(1)}%`;

  $('#panel').innerHTML = `
    <p class="crumbs">Console</p>
    <h1 class="ptitle">Where the system stands</h1>
    <p class="plede">
      Assembled by <span class="mono">build_registry.py</span> from ${esc(state.registry.recordsScanned)}
      governance records on disk. Nothing on this screen is typed by hand.
    </p>

    ${
      drift.length
        ? `<div class="flag"><strong>${drift.length} drift note${drift.length === 1 ? '' : 's'} from the generator.</strong>
           ${drift.map((d) => `<br>${esc(d.id)} — ${esc(d.reason)}`).join('')}</div>`
        : ''
    }

    <div class="grid" data-cols="4">
      <a class="card card--link" href="#/zone/review">
        <p class="card__k">Waiting on a decision</p>
        <p class="card__v">${queued.length}</p>
        <p class="card__note">${queued.length === 0 ? 'Nothing is blocked on you.' : queued.map((q) => esc(q.name)).join(', ')}</p>
      </a>
      <div class="card">
        <p class="card__k">Canonical items</p>
        <p class="card__v">${canonical}</p>
        <p class="card__note">Approved through a human gate.</p>
      </div>
      <div class="card">
        <p class="card__k">Decisions on record</p>
        <p class="card__v">${state.decisions.size}</p>
        <p class="card__note">Central registers, all signed.</p>
      </div>
      <div class="card">
        <p class="card__k">Current release</p>
        <p class="card__v card__v--sm">${esc(sysRelease)}</p>
        <p class="card__note">${esc(state.registry.system.currentReleaseState)} · production version not assigned</p>
      </div>
    </div>

    <div class="shead"><h2>Live consumer</h2><p>Is what's shipped the same as what's approved?</p></div>
    ${
      consumer
        ? `<div class="card">
             <p class="card__title">
               <span>${esc(consumer.name)}</span>
               <span class="badge" data-tone="${inSync ? 'go' : 'wait'}">${inSync ? 'In sync' : 'Behind'}</span>
             </p>
             <dl class="meta">
               <dt>Live at</dt><dd><a href="${esc(consumer.productionIntegration?.productionUrl ?? '#')}" target="_blank" rel="noopener">${esc(consumer.productionIntegration?.productionUrl ?? '—')}</a></dd>
               <dt>Running</dt><dd class="mono">${esc(consumerRelease ?? '—')}</dd>
               <dt>Deployed</dt><dd>${esc(consumer.productionIntegration?.deployedAt ?? '—')}</dd>
               <dt>Approved by</dt><dd>${esc(consumer.productionIntegration?.approvedBy ?? '—')}</dd>
             </dl>
           </div>`
        : '<div class="empty"><h3>No consumer registered</h3></div>'
    }

    <div class="shead"><h2>Coverage</h2><p>What the system covers today, and what is parked.</p></div>
    <div class="card">
      <div class="bar">
        <span data-tone="go" style="width:${pct(canonical)}"></span>
        <span data-tone="info" style="width:${pct(nonProduction)}"></span>
        <span data-tone="idle" style="width:${pct(deferred)}"></span>
      </div>
      <div class="barkey">
        <span><i data-tone="go"></i>${canonical} canonical</span>
        <span><i data-tone="info"></i>${nonProduction} direction only</span>
        <span><i data-tone="idle"></i>${deferred} deferred</span>
      </div>
      <p class="card__note">Deferred work is parked on purpose, not blocked or rejected.</p>
    </div>

    <div class="shead"><h2>Decision log</h2><p>${state.decisions.size} central records, newest first</p></div>
    <div class="log">
      ${decided
        .map(
          (record) => `<div class="log__row">
            <span class="log__date">${esc(String(record.approvedAt).slice(0, 10))}</span>
            <span class="log__title">${esc(record.title)}<span class="log__id">${esc(record.id)}</span></span>
            ${badge(record.status === 'approved' ? 'canonical' : 'candidate')}
          </div>`,
        )
        .join('')}
    </div>
  `;
}

/* ── Zone / item ─────────────────────────────────────────────── */

function renderZone(zone) {
  const groups = (zone.groups ?? []).filter((group) => group.items?.length);
  $('#panel').innerHTML = `
    <p class="crumbs">${esc(zone.label)}</p>
    <h1 class="ptitle">${esc(zone.label)}</h1>
    <p class="plede">${esc(zone.hint ?? '')}</p>
    ${
      groups.length
        ? groups
            .map(
              (group) => `
          ${groups.length > 1 ? shead(group.label) : ''}
          ${group.note ? `<p class="plede">${esc(group.note)}</p>` : ''}
          <div class="grid" data-cols="2">
            ${group.items
              .map(
                (item) => `<a class="card card--link" href="#/item/${esc(zone.id)}/${esc(item.id)}">
                  <p class="card__title"><span>${esc(item.name)}</span>${badge(item.status)}</p>
                  <p class="card__note">${esc(item.summary ?? '')}</p>
                </a>`,
              )
              .join('')}
          </div>`,
            )
            .join('')
        : `<div class="empty">
             <h3>Nothing here right now</h3>
             <p>When a record on disk is waiting on a decision, the generator puts it here automatically. Empty means nothing is blocked.</p>
           </div>`
    }
  `;
}

const shead = (title, note = '') =>
  `<div class="shead"><h2>${esc(title)}</h2><p>${esc(note)}</p></div>`;

function renderItem(item) {
  const record = item.record ?? {};
  const central = record.decisionId ? state.decisions.get(record.decisionId) : null;
  const approver = record.approver ?? record.approvedBy ?? central?.approvedBy;
  const approvedAt = record.approvedAt ?? record.reviewedAt ?? central?.approvedAt;
  const native = Boolean(PANELS[item.id]);

  $('#panel').innerHTML = `
    <p class="crumbs">${esc(item.zoneLabel)} · ${esc(item.groupLabel)}</p>
    <h1 class="ptitle">${esc(item.name)} ${badge(item.status)}</h1>
    <p class="plede">${esc(item.summary ?? '')}</p>

    ${item.flag ? `<div class="flag">${esc(item.flag)}</div>` : ''}

    <dl class="meta">
      <dt>State</dt><dd>${esc(statusLabel(item.status))} — ${esc(state.registry.statuses[item.status]?.meaning ?? '')}</dd>
      ${item.version ? `<dt>Version</dt><dd class="mono">${esc(item.version)}</dd>` : ''}
      ${record.decisionId || item.decisionId ? `<dt>Decision</dt><dd class="mono">${esc(record.decisionId ?? item.decisionId)}</dd>` : ''}
      ${record.gateId || item.gateId ? `<dt>Human gate</dt><dd class="mono">${esc(record.gateId ?? item.gateId)}</dd>` : ''}
      ${approvedAt ? `<dt>Decided</dt><dd>${esc(String(approvedAt).slice(0, 10))}${approver ? ` by ${esc(approver)}` : ''}</dd>` : ''}
      ${record.verdict ? `<dt>Verdict</dt><dd>${esc(record.verdict)}</dd>` : ''}
      ${item.statusSource ? `<dt>Evidence</dt><dd class="mono">${esc(item.statusSource)}</dd>` : ''}
      ${item.gateB ? `<dt>Gate B</dt><dd>${item.gateB.score}/${item.gateB.max} — passed</dd>` : ''}
      ${item.count ? `<dt>Contains</dt><dd>${item.count} items</dd>` : ''}
    </dl>

    ${record.note ? `${shead('Recorded note')}<p class="plede">“${esc(record.note)}”</p>` : ''}
    ${central?.summary ? `${shead('What was approved')}<p class="plede">${esc(central.summary)}</p>` : ''}

    ${
      item.href || (item.secondary ?? []).length
        ? `<div class="actions">
             ${item.href ? `<a class="btn ${native ? 'btn--quiet' : ''}" href="${esc(item.href)}" target="_blank" rel="noopener">Open ${native ? 'original page' : 'full page'} ↗</a>` : ''}
             ${(item.secondary ?? [])
               .map((link) => `<a class="btn btn--quiet" href="${esc(link.href)}" target="_blank" rel="noopener">${esc(link.label)} ↗</a>`)
               .join('')}
           </div>`
        : ''
    }

    ${native ? '<div id="native" class="native"><p class="card__note">Loading source…</p></div>' : ''}
    ${!native && !item.href ? '<div class="empty"><h3>Not built yet</h3><p>This is deferred work. It keeps a future contract and a human gate, but nothing has been produced.</p></div>' : ''}

    ${item.status === 'candidate' ? decisionPanel(item) : ''}
  `;

  if (item.status === 'candidate') wireDecision(item);
  if (native) renderNativePanel(item);
}

async function renderNativePanel(item) {
  const mount = $('#native');
  if (!mount) return;
  await renderPanel(item.id, mount);
}

/* ── How this works ──────────────────────────────────────────── */

function renderHow() {
  $('#panel').innerHTML = `
    <p class="crumbs">Console</p>
    <h1 class="ptitle">How this works</h1>
    <p class="plede">The whole operating model on one screen: what the states mean, how a decision
    happens, and where the truth for each thing lives.</p>

    ${shead('The states')}
    <dl class="meta">
      ${Object.entries(state.registry.statuses)
        .map(([key, meta]) => `<dt>${badge(key)}</dt><dd>${esc(meta.meaning)}</dd>`)
        .join('')}
    </dl>

    ${shead('How a decision happens', 'The lifecycle every item follows')}
    <div class="log">
      ${[
        ['1', 'Build', 'An agent builds a candidate from approved inputs. It has no authority yet.'],
        ['2', 'Queue', 'Its review.json says awaiting-human-review. The generator puts it in the Review zone automatically — nobody edits a list.'],
        ['3', 'Decide', 'A human (Olli) approves, requests changes or rejects — on the item page here, or by editing the record directly.'],
        ['4', 'Record', 'The verdict is written to the item’s review/approval file and appended to the central register. The decision id (DEC-…) is permanent evidence.'],
        ['5', 'Regenerate', 'python3 brand-kit/app/build_registry.py — the console now shows the new truth.'],
        ['6', 'Release', 'Approved work is assembled into a versioned, frozen release. Consumers only ever ingest releases, never the working tree.'],
      ]
        .map(
          ([step, title, body]) => `<div class="log__row log__row--bands">
            <span class="mono">${step}</span>
            <span class="log__title">${esc(title)}<span class="log__id">${esc(body)}</span></span>
            <span></span>
          </div>`,
        )
        .join('')}
    </div>

    ${shead('Where truth lives', 'One owner per kind of thing')}
    <dl class="meta">
      <dt>Tokens &amp; contracts</dt><dd><span class="mono">foundations/*/…source.json</span>, <span class="mono">expressions/*/…source.json</span> — the console renders these directly.</dd>
      <dt>Approval evidence</dt><dd><span class="mono">review.json</span> / <span class="mono">approval.json</span> beside each item, plus the central registers in <span class="mono">governance/</span>.</dd>
      <dt>Live artifacts</dt><dd>The canonical custom elements and the Living Core renderer — the console imports the real modules, it never copies them.</dd>
      <dt>Shipped output</dt><dd><span class="mono">releases/…</span> — frozen, versioned, integrity-tracked. What consumers ingest.</dd>
      <dt>This console</dt><dd><span class="mono">brand-kit/app/</span> — a renderer over all of the above. If the console disagrees with a record, the record wins.</dd>
    </dl>

    ${shead('The two-repo rule', 'Design system vs the live site')}
    <p class="plede">
      Shared identity — tokens, navigation, homepage composition, gradients — is decided here and
      consumed by the site as a frozen vendored release. Product and sales surfaces — /ai-os, ad
      variants, checkout — are owned by the site outright and never need approval here. See
      <a href="#/ingest">Consumers &amp; ingest</a> for the mechanics.
    </p>
  `;
}

/* ── Ingest ──────────────────────────────────────────────────── */

function renderIngest() {
  const consumer = state.consumers[0];
  const sysRelease = state.registry.system.currentRelease;
  const consumerRelease = consumer?.designSystemCandidate?.version;
  const inSync = consumerRelease === sysRelease;

  $('#panel').innerHTML = `
    <p class="crumbs">Console</p>
    <h1 class="ptitle">Consumers &amp; ingest</h1>
    <p class="plede">How the design system reaches a real website without creating a second
    source of truth: consumers vendor a frozen release, own their own surfaces, and never
    reach into this working tree.</p>

    ${shead('Registered consumers', 'From governance/consumer-register.json')}
    ${
      consumer
        ? `<div class="card">
             <p class="card__title">
               <span>${esc(consumer.name)}</span>
               <span class="badge" data-tone="${inSync ? 'go' : 'wait'}">${inSync ? `In sync · ${esc(sysRelease)}` : `Running ${esc(consumerRelease ?? '?')} · latest is ${esc(sysRelease)}`}</span>
             </p>
             <dl class="meta">
               <dt>Live at</dt><dd><a href="${esc(consumer.productionIntegration?.productionUrl ?? '#')}" target="_blank" rel="noopener">${esc(consumer.productionIntegration?.productionUrl ?? '—')}</a></dd>
               <dt>Repository</dt><dd class="mono">mezcorp-studio/ceos-notion-landingpage</dd>
               <dt>Vendored at</dt><dd class="mono">src/design-system/mez/${esc(consumerRelease ?? '?')}/</dd>
               <dt>Consumer owns</dt><dd>${esc(consumer.authorityBoundary?.consumerOwns ?? 'routes, analytics, SEO, commerce, deployment, content truth')}</dd>
               <dt>System owns</dt><dd>tokens, fonts, identity assets, Living Core runtime, component machinery, golden composition</dd>
             </dl>
           </div>`
        : '<div class="empty"><h3>No consumer registered</h3></div>'
    }

    ${shead('The rules', 'What keeps this safe')}
    <div class="log">
      ${[
        ['R1', 'Vendored files are immutable', 'The copy under src/design-system/mez/<version>/ is never hand-edited. Its own headers say so.'],
        ['R2', 'Overrides live in consumer CSS', 'Site-specific styling layers on top (consumer adapter files), loaded after the vendored CSS so it wins the cascade without touching it.'],
        ['R3', 'Consumer surfaces need no approval', '/ai-os, ad variants and checkout are the site’s own. Changing them never involves this repository.'],
        ['R4', 'Canonical components changed at the consumer should flow back', 'If the site improves the nav or homepage, either upstream the change here for approval or record it as a deliberate consumer deviation — silence is how drift happens.'],
        ['R5', 'Upgrades are re-vendors', 'When a new release cuts here, the site re-runs its vendor scripts against the new version, reconciles overrides, and bumps the register.'],
      ]
        .map(
          ([id, title, body]) => `<div class="log__row log__row--bands">
            <span class="mono">${id}</span>
            <span class="log__title">${esc(title)}<span class="log__id">${esc(body)}</span></span>
            <span></span>
          </div>`,
        )
        .join('')}
    </div>

    ${shead('Re-vendor steps', 'When a new release exists')}
    <div class="card">
      <ol class="steps">
        <li>Cut and freeze the release here: <span class="mono">releases/production-01/&lt;version&gt;/</span> with its manifest hash.</li>
        <li>In the site repo, point <span class="mono">scripts/mez/vendor-*.mjs</span> at the new version and run them.</li>
        <li>Diff the generated output; reconcile consumer override CSS against anything that moved.</li>
        <li>Run the site's <span class="mono">verify:mez-*</span> scripts and visual checks.</li>
        <li>Update <span class="mono">governance/consumer-register.json</span> here so the sync badge above goes green.</li>
      </ol>
    </div>

    ${shead('For agents', 'The paragraph that belongs in the site repo')}
    <p class="plede">
      The site repository's AGENTS.md points agents at this repository (checked out locally as a
      sibling) as the read-only source of truth for shared identity, and names the vendored
      version. An agent styling a canonical component checks the contract here first; an agent
      working on a consumer surface never needs to.
    </p>
  `;
}

/* ── Recording a decision ────────────────────────────────────── */

const VERDICTS = [
  { id: 'approve', label: 'Approve', status: 'approved', resulting: 'canonical', tone: 'go' },
  { id: 'revise', label: 'Request changes', status: 'deferred', resulting: 'review-candidate', tone: 'wait' },
  { id: 'reject', label: 'Reject', status: 'rejected', resulting: 'rejected', tone: 'alert' },
];

function decisionPanel(item) {
  const suggested = `DEC-${item.id.toUpperCase().replace(/[^A-Z0-9]+/g, '-')}-001`;
  return `
    ${shead('Record a decision', 'Produces the gate record and the register entry')}
    <div class="card decide" id="decide">
      <div class="decide__row">
        <span class="card__k">Verdict</span>
        <div class="choices" role="radiogroup" aria-label="Verdict">
          ${VERDICTS.map(
            (verdict, index) =>
              `<button type="button" class="choice" role="radio" data-verdict="${verdict.id}"
                       aria-checked="${index === 0}" data-tone="${verdict.tone}">${esc(verdict.label)}</button>`,
          ).join('')}
        </div>
      </div>
      <label class="field"><span class="card__k">Decision id</span>
        <input id="d-id" class="mono" value="${esc(suggested)}" spellcheck="false" />
        <small>Must match <code>^DEC-[A-Z0-9-]+$</code></small></label>
      <label class="field"><span class="card__k">Approver</span><input id="d-by" value="Olli" spellcheck="false" /></label>
      <label class="field"><span class="card__k">Scope — what this decision covers</span><input id="d-scope" value="${esc(item.name)}" /></label>
      <label class="field"><span class="card__k">Note</span>
        <textarea id="d-note" rows="3" placeholder="What you are approving, and anything explicitly excluded."></textarea></label>
      <label class="check"><input type="checkbox" id="d-auth" /><span>Grants production authority</span></label>
      <div id="d-errors"></div>
      <div class="actions">
        <button class="btn" type="button" id="d-build">Build records</button>
        <button class="btn btn--quiet" type="button" id="d-copy" disabled>Copy both</button>
        <button class="btn btn--quiet" type="button" id="d-dl" disabled>Download</button>
      </div>
      <div id="d-out"></div>
      <p class="card__note">After committing the records, run
        <span class="mono">python3 brand-kit/app/build_registry.py</span> and reload — the queue
        updates itself.</p>
    </div>
  `;
}

function wireDecision(item) {
  const root = $('#decide');
  if (!root) return;

  let verdict = VERDICTS[0];
  let built = null;

  root.querySelectorAll('[data-verdict]').forEach((button) => {
    button.addEventListener('click', () => {
      verdict = VERDICTS.find((entry) => entry.id === button.dataset.verdict);
      root.querySelectorAll('[data-verdict]').forEach((other) => {
        other.setAttribute('aria-checked', String(other === button));
      });
    });
  });

  $('#d-build').addEventListener('click', () => {
    const id = $('#d-id').value.trim();
    const by = $('#d-by').value.trim();
    const scope = $('#d-scope').value.trim();
    const note = $('#d-note').value.trim();
    const auth = $('#d-auth').checked;

    const errors = [];
    if (!/^DEC-[A-Z0-9-]+$/.test(id)) errors.push('Decision id must match ^DEC-[A-Z0-9-]+$');
    if (state.decisions.has(id)) errors.push(`${id} already exists — pick an unused id`);
    if (!by) errors.push('Approver is required');
    if (!scope) errors.push('Scope is required');
    if (!note) errors.push('Note is required — the record needs a summary');

    const errorBox = $('#d-errors');
    if (errors.length) {
      errorBox.innerHTML = `<div class="flag"><div>${errors.map(esc).join('<br>')}</div></div>`;
      $('#d-copy').disabled = true;
      $('#d-dl').disabled = true;
      return;
    }
    errorBox.innerHTML = '';

    const now = new Date();
    const day = now.toISOString().slice(0, 10);
    const recordPath = item.record?._source
      ? `brand-kit/${item.record._source}`
      : `brand-kit/components/${item.id}/review.json`;

    const gateRecord = {
      schemaVersion: '1.0.0',
      gateId: item.record?.gateId ?? item.gateId ?? null,
      taskId: item.record?.taskId ?? null,
      candidateRevision: item.record?.candidateRevision ?? null,
      verdict: verdict.status === 'approved' ? 'approved' : verdict.id,
      note,
      reviewedAt: now.toISOString(),
      approver: by,
      decisionId: verdict.status === 'approved' ? id : null,
      resultingStatus: verdict.resulting,
      productionAuthority: verdict.status === 'approved' ? auth : false,
    };

    const registerRecord = {
      id,
      title: item.name,
      status: verdict.status,
      scope,
      summary: note,
      approvedAt: day,
      approvedBy: by,
      source: recordPath,
    };

    built = {
      gate: { path: recordPath, body: gateRecord },
      register: { path: 'brand-kit/governance/post-cutover-decisions.json', body: registerRecord },
    };

    $('#d-out').innerHTML = `
      <div class="out">
        <p class="card__k">1 · Replace the gate record</p>
        <p class="outpath mono">${esc(built.gate.path)}</p>
        <pre class="mono">${esc(JSON.stringify(built.gate.body, null, 2))}</pre>
      </div>
      <div class="out">
        <p class="card__k">2 · Append to the central register</p>
        <p class="outpath mono">${esc(built.register.path)}</p>
        <pre class="mono">${esc(JSON.stringify(built.register.body, null, 2))}</pre>
      </div>
      <p class="card__note">Validated against <code>schemas/decision.schema.json</code>. Nothing is
        written by this screen — hand these to whoever commits, or save them yourself.</p>
    `;

    $('#d-copy').disabled = false;
    $('#d-dl').disabled = false;
  });

  $('#d-copy').addEventListener('click', async () => {
    if (!built) return;
    const text = `// ${built.gate.path}\n${JSON.stringify(built.gate.body, null, 2)}\n\n// ${built.register.path}\n${JSON.stringify(built.register.body, null, 2)}\n`;
    try {
      await navigator.clipboard.writeText(text);
      $('#d-copy').textContent = 'Copied';
      setTimeout(() => ($('#d-copy').textContent = 'Copy both'), 1600);
    } catch {
      $('#d-copy').textContent = 'Copy failed';
    }
  });

  $('#d-dl').addEventListener('click', () => {
    if (!built) return;
    const blob = new Blob([`${JSON.stringify(built, null, 2)}\n`], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${built.register.body.id.toLowerCase()}-decision.json`;
    link.click();
    URL.revokeObjectURL(url);
  });
}

/* ── Search ──────────────────────────────────────────────────── */

function wireSearch() {
  const input = $('#search');
  const results = $('#results');

  const close = () => {
    results.hidden = true;
    results.innerHTML = '';
  };

  input.addEventListener('input', () => {
    const query = input.value.trim().toLowerCase();
    if (query.length < 2) return close();

    const hits = state.flat
      .filter((item) =>
        [item.name, item.summary, item.record?.decisionId, item.groupLabel, item.zoneLabel]
          .filter(Boolean)
          .some((field) => String(field).toLowerCase().includes(query)),
      )
      .slice(0, 10);

    if (!hits.length) {
      results.innerHTML = '<button type="button" disabled>No matches</button>';
      results.hidden = false;
      return;
    }

    results.innerHTML = hits
      .map(
        (item) => `<button type="button" data-go="#/item/${esc(item.zoneId)}/${esc(item.id)}">
            <span>${esc(item.name)}<br><span class="r-path">${esc(item.zoneLabel)} · ${esc(item.groupLabel)}</span></span>
            ${badge(item.status)}
          </button>`,
      )
      .join('');
    results.hidden = false;
  });

  results.addEventListener('click', (event) => {
    const button = event.target.closest('[data-go]');
    if (!button) return;
    location.hash = button.dataset.go;
    input.value = '';
    close();
  });

  input.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') {
      input.value = '';
      close();
      input.blur();
    }
  });

  document.addEventListener('click', (event) => {
    if (!event.target.closest('.topbar__search')) close();
  });
}

boot();
