/** Mez Systems · EXP-08 Expression Stress Proof · canonical 1.0.0. */
import { mountLivingCores } from "../../../source-pack/design-system-export/mz-core.js";

const STATIC_BASE = "../../../gradient-library/assets/static/";
const WINGS_URL = "../../../source-pack/design-system-export/assets/wings.svg";
const query = new URLSearchParams(location.search);
const prefersReduced = matchMedia("(prefers-reduced-motion: reduce)").matches;
const forcedStatic = query.has("static") || prefersReduced;
const forcedNoWebGL = query.has("no-webgl");
const suites = [
  {id:"reflow",title:"Receiver and reflow",rule:"No overflow, clipping, overlap or unusable control."},
  {id:"content",title:"Content and zoom",rule:"Hierarchy and actions survive growth, translation and RTL."},
  {id:"fallback",title:"Motion and fallback",rule:"Every moving state has a complete static equivalent."},
  {id:"accessibility",title:"Accessibility and input",rule:"Meaning and operation survive keyboard, touch and non-colour use."},
  {id:"recovery",title:"Async and recovery",rule:"Incomplete and failed states stay truthful and recoverable."},
  {id:"invariants",title:"System invariants",rule:"Canonical identity stays fixed and maximum one live material moves."}
];
const scenarios = [
  {id:"ST-R01",suite:"reflow",title:"240px compact receiver",type:"pricing",badge:"240 PX"},
  {id:"ST-R02",suite:"reflow",title:"320px mobile decision",type:"mobile",badge:"320 PX"},
  {id:"ST-R03",suite:"reflow",title:"1440px family shelf",type:"shelf",badge:"1440 PX"},
  {id:"ST-T01",suite:"content",title:"200% text zoom",type:"checkout",badge:"200%"},
  {id:"ST-T02",suite:"content",title:"400% text zoom",type:"discovery",badge:"400%"},
  {id:"ST-T03",suite:"content",title:"Long, localized and RTL copy",type:"localized",badge:"RTL / L10N"},
  {id:"ST-F01",suite:"fallback",title:"Reduced motion",type:"static",badge:"REDUCE"},
  {id:"ST-F02",suite:"fallback",title:"WebGL unavailable",type:"fallback",badge:"NO WEBGL"},
  {id:"ST-F03",suite:"fallback",title:"Missing media",type:"missing",badge:"NO MEDIA"},
  {id:"ST-A01",suite:"accessibility",title:"Keyboard and focus",type:"keyboard",badge:"TAB / ESC"},
  {id:"ST-A02",suite:"accessibility",title:"Touch and non-colour meaning",type:"touch",badge:"44 PX"},
  {id:"ST-S01",suite:"recovery",title:"Loading, failure and retry",type:"recovery",badge:"ERROR → RETRY"},
  {id:"ST-S02",suite:"recovery",title:"Missing optional data and unpriced offer",type:"unpriced",badge:"NO PRICE"},
  {id:"ST-I01",suite:"invariants",title:"One live core across repetition",type:"allocation",badge:"MAX 1 LIVE"}
];

const h=(tag,className="",text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const wings=()=>{const image=h("img","wings");image.src=WINGS_URL;image.alt="";return image;};
const material=(product,{live=false,missing=false}={})=>{const node=h("div",`material${missing?" is-missing":""}`);node.dataset.gradientId=product.gradientId;node.style.setProperty("--field",`url('${STATIC_BASE}${product.gradientId.toLowerCase()}.webp')`);if(live)node.dataset.coreHost="";node.append(wings());if(missing)node.append(h("span","media-status","Product material unavailable · identity retained"));return node;};
const action=(label="Explore the system")=>{const button=h("button","action",label);button.type="button";return button;};
const copy=(product,long=false)=>{const node=h("div","product-copy");node.append(h("h4","",product.publicName),h("span","extended",product.function),h("p","",long?"A deliberately expanded explanation proving that product meaning, supporting context and the primary decision remain complete when the copy becomes much longer than the preferred editorial length.":product.summary),action());return node;};

function productCard(product,options={}){const card=h("article","product-card");card.append(material(product,options),copy(product,options.long));return card;}
function pricing(product){const card=h("article","price-card");card.append(h("span","eyebrow","ONE-TIME ACCESS"),h("h4","",product.publicName),h("p","",product.summary),h("strong","price","$249"),h("small","","Tax calculated at checkout"),action("Get the system"));return card;}
function mobile(product){const phone=h("div","phone"),sticky=h("div","sticky-action");sticky.append(action("Continue"));phone.append(material(product),copy(product),sticky);return phone;}
function shelf(products){const rail=h("div","family-shelf");products.slice(0,4).forEach((product,index)=>rail.append(productCard(product,{live:index===0})));return rail;}
function checkout(product){const shell=h("div","checkout");const form=h("form");form.append(h("h4","","Complete access"));["Email address","Cardholder name"].forEach(label=>{const field=h("label");field.append(h("span","",label),h("input"));form.append(field);});form.append(action("Complete purchase"));const summary=h("aside");summary.append(h("span","eyebrow","ORDER SUMMARY"),h("strong","",product.publicName),h("p","",product.function),h("b","","$249"));shell.append(form,summary);return shell;}
function localized(product){const card=productCard({...product,publicName:"نظام تشغيل الذكاء الاصطناعي",function:"نظام تشغيل متكامل للذكاء الاصطناعي",summary:"سياق موسّع لاختبار الترجمة واتجاه القراءة والمسافات المنطقية داخل البطاقة."},{long:true});card.dir="rtl";card.lang="ar";return card;}
function keyboard(product){const shell=h("div","keyboard-demo");shell.append(h("h4","","Choose a product"));[product.publicName,"Context Engine","Claude Code OS"].forEach((label,index)=>{const button=action(label);button.setAttribute("aria-pressed",String(index===0));shell.append(button);});return shell;}
function touch(){const shell=h("div","touch-demo");const label=h("label");label.append(h("span","","Notify me when available"));const input=h("input");input.type="checkbox";label.append(input);shell.append(h("strong","status-text","Coming soon — not available for purchase"),label,action("Join waitlist"));return shell;}
function recovery(product){const shell=h("div","recovery"),status=h("div","error-status");status.setAttribute("role","status");status.setAttribute("aria-live","polite");status.append(h("strong","","Payment was not completed"),h("p","","Your product and order details are still here. No charge was made."));const retry=action("Try again");retry.dataset.retry="";shell.append(productCard(product),status,retry);return shell;}
function unpriced(product){const card=h("article","unpriced");card.append(material(product),h("span","eyebrow","CUSTOM SCOPE"),h("h4","",product.publicName),h("p","","Pricing depends on the operating scope. No amount is invented here."),h("strong","status-text","Talk to us for a scoped offer"),action("Discuss your system"));return card;}
function allocation(products){const rail=h("div","allocation");products.slice(0,3).forEach((product,index)=>rail.append(productCard(product,{live:index===0})));const note=h("p","allocation-note","maximum one live · two exact static siblings");rail.append(note);return rail;}

function visual(spec,products){const product=products[spec.id.charCodeAt(spec.id.length-1)%products.length];
  if(spec.type==="pricing")return pricing(product);if(spec.type==="mobile")return mobile(product);if(spec.type==="shelf")return shelf(products);if(spec.type==="checkout")return checkout(product);if(spec.type==="discovery")return productCard(product,{long:true});if(spec.type==="localized")return localized(product);if(spec.type==="static")return productCard(product);if(spec.type==="fallback")return productCard(product,{live:true});if(spec.type==="missing")return productCard(product,{missing:true});if(spec.type==="keyboard")return keyboard(product);if(spec.type==="touch")return touch();if(spec.type==="recovery")return recovery(product);if(spec.type==="unpriced")return unpriced(product);return allocation(products);}

function render(products){const root=document.querySelector("[data-suites]");suites.forEach((suite,index)=>{const section=h("section","suite");section.id=suite.id;const head=h("header","suite-head");head.append(h("span","suite-number",String(index+1).padStart(2,"0")));const title=h("div");title.append(h("p","meta",`${scenarios.filter(item=>item.suite===suite.id).length} PROOFS`),h("h3","",suite.title),h("p","",suite.rule));head.append(title);const grid=h("div","scenario-grid");scenarios.filter(item=>item.suite===suite.id).forEach(spec=>{const article=h("article","scenario");article.dataset.scenarioId=spec.id;const label=h("header","scenario-label");label.append(h("span","scenario-id",spec.id),h("h4","",spec.title),h("b","",spec.badge));const receiver=h("div","scenario-receiver");receiver.append(visual(spec,products));const checks=h("footer","scenario-checks");checks.append(h("span","check","✓ Complete state"),h("span","check","✓ Meaning retained"),h("span","check","✓ Recovery present"));article.append(label,receiver,checks);grid.append(article);});section.append(head,grid);root.append(section);});}

function applyControls(){const controls=document.querySelector(".control-deck"),receiver=controls.querySelector("[data-receiver]").value,scale=controls.querySelector("[data-scale]").value,content=controls.querySelector("[data-content]").value,runtime=controls.querySelector("[data-runtime]").value;document.documentElement.style.setProperty("--lab-width",`${receiver}px`);document.documentElement.style.setProperty("--font-scale",scale);document.documentElement.dataset.content=content;document.documentElement.dataset.runtime=runtime;document.documentElement.dir=content==="rtl"?"rtl":"ltr";document.querySelector("[data-mode]").textContent=`Receiver ${receiver}px · Text ${Number(scale)*100}% · ${content} content · ${runtime} runtime`;document.querySelector("[data-summary]").innerHTML=`<strong>14 / 14</strong><span>fixtures mounted</span><strong>${runtime==="default"&&!forcedStatic?"1":"0"}</strong><span>live materials allocated</span><strong>0</strong><span>approved decisions changed</span>`;}

function bind(){document.querySelectorAll(".control-deck select").forEach(select=>select.addEventListener("change",applyControls));document.addEventListener("click",event=>{const retry=event.target.closest("[data-retry]");if(retry){const status=retry.parentElement.querySelector("[aria-live]");status.classList.add("is-recovered");status.querySelector("strong").textContent="Ready to try again";status.querySelector("p").textContent="Order context retained. Choose the payment action when ready.";retry.textContent="Complete purchase";}});const panel=document.querySelector("#review-panel"),trigger=document.querySelector("[data-review-open]");const toggle=open=>{document.body.classList.toggle("is-reviewing",open);panel.setAttribute("aria-hidden",String(!open));trigger.setAttribute("aria-expanded",String(open));if(open)panel.querySelector("[data-review-close]").focus();else trigger.focus();};document.addEventListener("click",event=>{if(event.target.closest("[data-review-open]"))toggle(true);if(event.target.closest("[data-review-close]"))toggle(false);});addEventListener("keydown",event=>{if(event.key==="Escape"&&document.body.classList.contains("is-reviewing"))toggle(false);});document.querySelector("[data-export]").addEventListener("click",async event=>{const payload={schemaVersion:"1.0.0",gateId:"H-EXP-08-EXPRESSION-STRESS-PROOF",taskId:"TASK-EXP-08-EXPRESSION-STRESS-PROOF",proofId:"mz.systems.expression.stress-proof",candidateRevision:"expression-stress-01-r01",verdict:"approve",approvedSuites:6,approvedScenarios:14,note:"Close EXP-08 and proceed to TASK-CMP-01-GLOBAL-NAVIGATION. Real consumer, provider and payment proof remains separate.",reviewedAt:"2026-07-23T01:32:07Z",approver:"Olli",decisionId:"DEC-EXPRESSION-STRESS-CERTIFICATION-001",resultingStatus:"canonical",productionAuthority:true};const output=JSON.stringify(payload,null,2);document.querySelector("[data-review-output]").textContent=output;try{await navigator.clipboard.writeText(output);event.target.textContent="Copied";}catch{event.target.textContent="Approval ready below";}});}

async function initialiseCore(){if(forcedStatic||forcedNoWebGL)return;try{const response=await fetch("../../../gradient-library/catalogue.json");const catalogue=await response.json();const hosts=[...document.querySelectorAll("[data-core-host]")];hosts.slice(1).forEach(host=>host.removeAttribute("data-core-host"));const host=hosts[0];if(!host)return;const mounted=await mountLivingCores(document,{catalogue,staticBaseUrl:"../../../gradient-library/assets/static/"});const size=Math.min(host.clientWidth,host.clientHeight)||210;mounted.renderer.mount(host,host.dataset.gradientId,{shape:"rect",radius:Math.min(.3,24/(size/2)),profile:"deep"});host.dataset.mzCore=host.dataset.gradientId;}catch(error){document.documentElement.dataset.coreError=error?.message||"unknown";}}
async function main(){const response=await fetch("../../../registry/products.json");const {products}=await response.json();render(products);if(document.querySelectorAll("[data-scenario-id]").length!==14)throw new Error("Expected 14 stress scenarios");bind();applyControls();await initialiseCore();}
main().catch(error=>{console.error(error);document.body.prepend(h("p","render-failure",`Stress proof failed: ${error.message}`));});

export const canonicalAuthority = {productionAuthority:true, decisionId:"DEC-EXPRESSION-STRESS-CERTIFICATION-001", rule:"maximum one live material"};
